# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645 \u06a9\u0627\u0631\u0628\u0631')),
                ('last_name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645 \u062e\u0627\u0646\u0648\u0627\u062f\u06af\u06cc')),
                ('code', models.CharField(default=myapp.models._createHash, max_length=10, unique=True)),
                ('tel', models.CharField(help_text='\u0628\u0647 \u0647\u0645\u0631\u0627\u0647 \u06a9\u062f \u0634\u0647\u0631 \u0628\u0647 \u0635\u0648\u0631\u062a 025387654321', max_length=14, verbose_name='\u062a\u0644\u0641\u0646 \u0645\u0646\u0632\u0644')),
                ('mobile', models.CharField(max_length=50, verbose_name='\u062a\u0644\u0641\u0646 \u0647\u0645\u0631\u0627\u0647')),
                ('img', models.ImageField(default='images/gallery/portal2.jpg', upload_to='images/profile/', verbose_name='\u0639\u06a9\u0633 \u06a9\u0627\u0631\u0628\u0631')),
                ('score', models.IntegerField(default=0, verbose_name='\u0627\u0645\u062a\u06cc\u0627\u0632')),
            ],
            options={
                'verbose_name': '\u06a9\u0627\u0631\u0628\u0631',
                'verbose_name_plural': '\u06a9\u0627\u0631\u0628\u0631\u0627\u0646',
            },
        ),
    ]
