# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=myapp.models._createHash, max_length=30, unique=True),
        ),
    ]
