# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=b'f472d67e0a', max_length=10, unique=True, verbose_name='\u0646\u0627\u0645 \u06a9\u0627\u0631\u0628\u0631\u06cc'),
        ),
    ]
