# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170217_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='username',
        ),
    ]
