# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170223_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=myapp.models._createHash, max_length=10, unique=True, verbose_name='\u0646\u0627\u0645 \u06a9\u0627\u0631\u0628\u0631\u06cc'),
        ),
    ]
