# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170223_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646 \u062c\u0627\u06cc\u0632\u0647')),
                ('description', models.TextField(verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a')),
                ('img', models.ImageField(default='images/gallery/award.jpg', upload_to='images/awards/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u062c\u0627\u06cc\u0632\u0647')),
                ('min_score', models.IntegerField(verbose_name='\u062d\u062f\u0627\u0642\u0644 \u0627\u0645\u062a\u06cc\u0627\u0632')),
                ('max_score', models.IntegerField(verbose_name='\u062d\u062f\u0627\u06a9\u062b\u0631 \u0627\u0645\u062a\u06cc\u0627\u0632')),
                ('number', models.IntegerField(verbose_name='\u062a\u0639\u062f\u0627\u062f \u0646\u0641\u0631\u0627\u062a')),
                ('active', models.BooleanField(default=True, verbose_name='\u0648\u0636\u0639\u06cc\u062a \u0641\u0639\u0627\u0644 \u0628\u0648\u062f\u0646')),
            ],
        ),
        migrations.CreateModel(
            name='UserAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='myapp.Awards', verbose_name='\u062c\u0627\u06cc\u0632\u0647')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.BooleanField(default=False, verbose_name='\u0648\u0636\u0639\u06cc\u062a \u0628\u0631\u062f'),
        ),
        migrations.AddField(
            model_name='userawards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='\u06a9\u0627\u0631\u0628\u0631'),
        ),
    ]
