# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170217_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=30, verbose_name='\u0631\u0645\u0632 \u0639\u0628\u0648\u0631'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spin',
            field=models.IntegerField(default=0, verbose_name='\u0645\u062c\u0645\u0648\u0639 \u0686\u0631\u062e\u0634 \u0647\u0627'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=myapp.models._createHash, max_length=30, unique=True, verbose_name='\u0646\u0627\u0645 \u06a9\u0627\u0631\u0628\u0631\u06cc'),
        ),
    ]
