# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170217_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_spin',
            field=models.IntegerField(verbose_name='\u0645\u062c\u0645\u0648\u0639 \u0686\u0631\u062e\u0634 \u0647\u0627'),
        ),
    ]
