# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170225_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name': '\u062c\u0627\u06cc\u0632\u0647', 'verbose_name_plural': '\u062c\u0648\u0627\u06cc\u0632'},
        ),
        migrations.AlterModelOptions(
            name='userawards',
            options={'verbose_name': '\u0628\u0631\u0646\u062f\u0647', 'verbose_name_plural': '\u0628\u0631\u0646\u062f\u0647 \u0647\u0627'},
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='name',
            new_name='title',
        ),
    ]
