# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170225_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.TextField(default='', verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a'),
        ),
    ]
