# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170228_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646 \u0642\u0631\u0639\u0647 \u06a9\u0634\u06cc')),
                ('description', models.TextField(default='', verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a')),
                ('active', models.BooleanField(default=True, verbose_name='\u0648\u0636\u0639\u06cc\u062a \u0641\u0639\u0627\u0644 \u0628\u0648\u062f\u0646')),
            ],
            options={
                'verbose_name': '\u0642\u0631\u0639\u0647 \u06a9\u0634\u06cc',
                'verbose_name_plural': '\u0642\u0631\u0639\u0647 \u06a9\u0634\u06cc \u0647\u0627',
            },
        ),
    ]
