# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=50, verbose_name='\u0646\u0627\u0645 \u062f\u0633\u062a\u0647')),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u06af\u0627\u0644\u0631\u06cc',
                'verbose_name_plural': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u06af\u0627\u0644\u0631\u06cc',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9')),
                ('large_img', models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af')),
                ('alt', models.CharField(default='', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category', verbose_name='\u06af\u0631\u0648\u0647')),
            ],
            options={
                'ordering': ['upload_date'],
                'verbose_name': '\u06af\u0627\u0644\u0631\u06cc \u062a\u0635\u0627\u0648\u06cc\u0631',
                'verbose_name_plural': '\u06af\u0627\u0644\u0631\u06cc \u062a\u0635\u0627\u0648\u06cc\u0631',
            },
        ),
    ]
