# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170309_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='\u062a\u0627\u0631\u06cc\u062e\u0686\u0647 \u0634\u0631\u06a9\u062a')),
                ('sales_office', models.CharField(max_length=250, verbose_name='\u0622\u062f\u0631\u0633 \u062f\u0641\u062a\u0631 \u0641\u0631\u0648\u0634 \u0645\u0631\u06a9\u0632\u06cc')),
                ('factory_address', models.CharField(max_length=350, verbose_name='\u0622\u062f\u0631\u0633 \u06a9\u0627\u0631\u062e\u0627\u0646\u0647')),
                ('email', models.EmailField(max_length=254, verbose_name='\u0627\u06cc\u0645\u06cc\u0644')),
                ('tel_1', models.CharField(max_length=14, verbose_name='\u062a\u0644\u0641\u0646')),
                ('tel_2', models.CharField(max_length=14, verbose_name='\u062a\u0644\u0641\u0646')),
                ('postal_code', models.CharField(max_length=20, verbose_name='\u06a9\u062f \u067e\u0633\u062a\u06cc')),
                ('fax', models.CharField(max_length=20, verbose_name='\u0641\u0627\u06a9\u0633')),
                ('site', models.URLField(verbose_name='\u0633\u0627\u06cc\u062a \u0641\u0631\u0648\u0634 \u0641\u0631\u0627\u0648\u0631\u062f\u0647 \u0647\u0627\u06cc \u06af\u0648\u0634\u062a\u06cc \u0634\u06a9\u0648\u0647\u06cc\u0647 (\u06f8\u06f0\u06f8)')),
            ],
            options={
                'verbose_name': '\u062f\u0631\u0628\u0627\u0631\u0647 \u0645\u0627',
                'verbose_name_plural': '\u062f\u0631\u0628\u0627\u0631\u0647 \u0645\u0627',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350, verbose_name='\u0645\u062a\u0646')),
            ],
            options={
                'verbose_name': '\u0647\u062f\u0641 \u0634\u0631\u06a9\u062a',
                'verbose_name_plural': '\u0627\u0647\u062f\u0627\u0641 \u0634\u0631\u06a9\u062a',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350, verbose_name='\u0645\u062a\u0646')),
            ],
            options={
                'verbose_name': '\u0646\u0642\u0627\u0637 \u0642\u0648\u062a \u0634\u0631\u06a9\u062a',
                'verbose_name_plural': '\u0646\u0642\u0627\u0637 \u0642\u0648\u062a \u0634\u0631\u06a9\u062a',
            },
        ),
    ]
