# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170312_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='images/gallery/user.jpg', help_text='\u0627\u0646\u062f\u0627\u0632\u0647 \u062a\u0635\u0648\u06cc\u0631: 128 * 128 \u067e\u06cc\u06a9\u0633\u0644', upload_to='images/profile/', verbose_name='\u0639\u06a9\u0633 \u06a9\u0627\u0631\u0628\u0631'),
        ),
    ]
