# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170312_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25, verbose_name='\u0639\u0646\u0648\u0627\u0646 \u062e\u0628\u0631')),
                ('img', models.ImageField(help_text='size(100px * 100px)', upload_to='images/news/', verbose_name='\ufe96\ufebb\ufeed\u06cc\ufead')),
                ('summary', models.CharField(max_length=200, verbose_name='\u062e\u0644\u0627\u0635\u0647 \u062e\u0628\u0631')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': '\u062e\u0628\u0631',
                'verbose_name_plural': '\u0627\u062e\u0628\u0627\u0631',
            },
        ),
    ]
