# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20170613_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(help_text='\u062d\u062f\u0627\u06a9\u062b\u0631 \u06f2\u06f2\u06f0 \u06a9\u0627\u0631\u0627\u06a9\u062a\u0631', max_length=250, verbose_name='\u062e\u0644\u0627\u0635\u0647 \u062e\u0628\u0631'),
        ),
    ]
